### PR TITLE
Expose `Project`'s source sets for Gradle versions prior to 7.1.

### PR DESCRIPTION
**Pull request by armiol**
This changeset updates the way in which we access the source sets of a Gradle `Project`.

Prior to this PR, we have relied upon `JavaPluginExtension.sourceSets` property. However, it only appeared in Gradle 7.1. So for Spine 1.9.x working on Gradle 6.9.x, an attempt to apply ProtoData or any other plugin based `tool-base`s code, results in `NoSuchMethodError`.

This pull request appends a fallback: if `NoSuchMethodError` is risen upon reading `sourceSets`, we now use a designated approach for Gradle versions prior to 7.1:

```kotlin
   project.convention
       .getByType(JavaPluginConvention::class.java)
       .sourceSets
```
This API is now deprecated by Gradle, so a respective warning was suppressed.

The version of the library is set to `2.0.0-SNAPSHOT.214`.

### CODE REVIEW

**Review by alexander-yevsyukov — APPROVED** [review]
LGTM
